### ISSUE TITLE
Please advise me what is problem?

### ISSUE THREAD

**Issue by anytrade** [doublenine99/QR-Code-Ordering-System#58]
npm WARN @bugsnag/plugin-react@6.4.0 requires a peer of @bugsnag/js@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-material-ui@1.30.1 requires a peer of react-native-vector-icons@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-paper@3.2.1 requires a peer of react-native-vector-icons@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by doublenine99** [comment]
> npm WARN @bugsnag/plugin-react@6.4.0 requires a peer of @bugsnag/js@* but none is installed. You must install peer dependencies yourself.
> npm WARN react-native-material-ui@1.30.1 requires a peer of react-native-vector-icons@^4.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-native-paper@3.2.1 requires a peer of react-native-vector-icons@* but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Sorry I think that's because the RN part code is migrated from other repo and the package.json has some problems, you can try install dependencies and edit the package file by yourself first. I would fix the packge.json later sometime later

**Comment by anytrade** [comment]
Hi ! My name is Peter and Can I talk to you? my Whatsapp +34610396136 wechat  anytrade

**Comment by anytrade** [comment]
> Hi ! My name is Peter and Can I talk to you? my Whatsapp +34610396136 wechat anytrade
